Update scrying.json
updated to correct parameters and requiring sudo 
``thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError("Permission denied (os error 13)")', src/web/linux.rs:226:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^CGdk-Message: 18:16:14.987: scrying: Fatal IO error 11 (Resource temporarily unavailable) on X server :99.``